### ISSUE TITLE
compilation fails on windows

### ISSUE THREAD

**Issue by vnt-dev** [yoshd/stun_client#19]
LINK : fatal error LNK1181: cannot open input file 'Packet.lib'

**Comment by yoshd** [comment]
@lbl8603 
Thank you for reporting this issue.
This seems to be a requirement by the dependency library libpnet, which requires the installation of WinPcap or npcap on Windows.
Additionally, please configure to link the `Packet.lib` downloaded from the [WinPcap Developers pack](https://www.winpcap.org/devel.htm).
For more details, please refer to the README of libpnet.
https://github.com/libpnet/libpnet#windows

Also, I'm considering adding a link to this procedure in the README!
Thank you!
